/// How to draw a boss's death animation (see BossComponent._die): the dying
/// frames live in [dir] (one PNG per frame) on a canvas that shares the walk
/// crop's pixel scale and horizontal center — so a fallen boss keeps its size —
/// but is wider/taller where the fall needs it. [heightFactor] is canvas
/// height / walk-crop height, [bottomFactor] how far the canvas bottom sits
/// below the walk crop's bottom (as a fraction of walk height), and [aspect]
/// the canvas width / height. Generated by the asset pipeline — do not edit
/// by hand.
class BossDeathSpec {
  const BossDeathSpec({
    required this.dir,
    required this.aspect,
    required this.heightFactor,
    required this.bottomFactor,
  });

  final String dir;
  final double aspect;
  final double heightFactor;
  final double bottomFactor;
}

/// Keyed by BossType.id.
const Map<String, BossDeathSpec> kBossDeathSpecs = {
  'golem2': BossDeathSpec(dir: 'bosses/death_golem2', aspect: 1.1715, heightFactor: 1.2191, bottomFactor: 0.0936),
  'golem1': BossDeathSpec(dir: 'bosses/death_golem1', aspect: 0.9986, heightFactor: 1.3087, bottomFactor: 0.1426),
  'golem3': BossDeathSpec(dir: 'bosses/death_golem3', aspect: 1.0633, heightFactor: 1.2597, bottomFactor: 0.0965),
  'goblin': BossDeathSpec(dir: 'bosses/death_goblin', aspect: 1.0057, heightFactor: 1.2897, bottomFactor: 0.1365),
  'ogre': BossDeathSpec(dir: 'bosses/death_ogre', aspect: 1.0987, heightFactor: 1.2527, bottomFactor: 0.1113),
  'orc': BossDeathSpec(dir: 'bosses/death_orc', aspect: 1.1140, heightFactor: 1.2529, bottomFactor: 0.1215),
  'wraith_emerald': BossDeathSpec(dir: 'bosses/death_wraith_emerald', aspect: 1.2166, heightFactor: 1.1993, bottomFactor: 0.1566),
  'wraith_wanderer': BossDeathSpec(dir: 'bosses/death_wraith_wanderer', aspect: 1.1754, heightFactor: 1.2042, bottomFactor: 0.1690),
  'wraith_shadow': BossDeathSpec(dir: 'bosses/death_wraith_shadow', aspect: 1.1092, heightFactor: 1.2268, bottomFactor: 0.1924),
  'caveman': BossDeathSpec(dir: 'bosses/death_caveman', aspect: 0.7713, heightFactor: 1.0858, bottomFactor: 0.0858),
  'giant_goblin': BossDeathSpec(dir: 'bosses/death_giant_goblin', aspect: 0.8241, heightFactor: 1.0181, bottomFactor: 0.0181),
  'viking': BossDeathSpec(dir: 'bosses/death_viking', aspect: 0.7856, heightFactor: 1.0828, bottomFactor: 0.0828),
  'goblin_chief': BossDeathSpec(dir: 'bosses/death_goblin_chief', aspect: 0.7429, heightFactor: 1.1346, bottomFactor: 0.1346),
  'ogre_shaman': BossDeathSpec(dir: 'bosses/death_ogre_shaman', aspect: 0.7623, heightFactor: 1.0583, bottomFactor: 0.0583),
  'orc_warrior': BossDeathSpec(dir: 'bosses/death_orc_warrior', aspect: 0.8539, heightFactor: 1.0657, bottomFactor: 0.0657),
  'valkyrie_steel': BossDeathSpec(dir: 'bosses/death_valkyrie_steel', aspect: 0.9634, heightFactor: 1.2857, bottomFactor: 0.2101),
  'valkyrie_storm': BossDeathSpec(dir: 'bosses/death_valkyrie_storm', aspect: 0.9596, heightFactor: 1.3270, bottomFactor: 0.2266),
  'valkyrie_golden': BossDeathSpec(dir: 'bosses/death_valkyrie_golden', aspect: 0.9822, heightFactor: 1.2956, bottomFactor: 0.2088),
  'oracle_ember': BossDeathSpec(dir: 'bosses/death_oracle_ember', aspect: 1.0746, heightFactor: 1.2840, bottomFactor: 0.1446),
  'oracle_lunar': BossDeathSpec(dir: 'bosses/death_oracle_lunar', aspect: 1.0544, heightFactor: 1.2783, bottomFactor: 0.1391),
  'oracle_starry': BossDeathSpec(dir: 'bosses/death_oracle_starry', aspect: 1.0984, heightFactor: 1.2708, bottomFactor: 0.1302),
};
