/// ISO 3166-1 alpha-2 country list for the register form's country picker.
/// A fixed list (rather than free text) keeps the data clean for the
/// `country_code` column in `users` — "Peru", "peru" and "PE" would
/// otherwise all end up as different values.
class Country {
  const Country(this.code, this.nameEs, this.nameEn);

  final String code;
  final String nameEs;
  final String nameEn;
}

const List<Country> kCountries = [
  Country('AF', 'Afganistán', 'Afghanistan'),
  Country('AL', 'Albania', 'Albania'),
  Country('DE', 'Alemania', 'Germany'),
  Country('AD', 'Andorra', 'Andorra'),
  Country('AO', 'Angola', 'Angola'),
  Country('AG', 'Antigua y Barbuda', 'Antigua and Barbuda'),
  Country('SA', 'Arabia Saudita', 'Saudi Arabia'),
  Country('DZ', 'Argelia', 'Algeria'),
  Country('AR', 'Argentina', 'Argentina'),
  Country('AM', 'Armenia', 'Armenia'),
  Country('AU', 'Australia', 'Australia'),
  Country('AT', 'Austria', 'Austria'),
  Country('AZ', 'Azerbaiyán', 'Azerbaijan'),
  Country('BS', 'Bahamas', 'Bahamas'),
  Country('BD', 'Bangladés', 'Bangladesh'),
  Country('BB', 'Barbados', 'Barbados'),
  Country('BH', 'Baréin', 'Bahrain'),
  Country('BE', 'Bélgica', 'Belgium'),
  Country('BZ', 'Belice', 'Belize'),
  Country('BJ', 'Benín', 'Benin'),
  Country('BY', 'Bielorrusia', 'Belarus'),
  Country('MM', 'Myanmar', 'Myanmar'),
  Country('BO', 'Bolivia', 'Bolivia'),
  Country('BA', 'Bosnia y Herzegovina', 'Bosnia and Herzegovina'),
  Country('BW', 'Botsuana', 'Botswana'),
  Country('BR', 'Brasil', 'Brazil'),
  Country('BN', 'Brunéi', 'Brunei'),
  Country('BG', 'Bulgaria', 'Bulgaria'),
  Country('BF', 'Burkina Faso', 'Burkina Faso'),
  Country('BI', 'Burundi', 'Burundi'),
  Country('BT', 'Bután', 'Bhutan'),
  Country('CV', 'Cabo Verde', 'Cape Verde'),
  Country('KH', 'Camboya', 'Cambodia'),
  Country('CM', 'Camerún', 'Cameroon'),
  Country('CA', 'Canadá', 'Canada'),
  Country('QA', 'Catar', 'Qatar'),
  Country('TD', 'Chad', 'Chad'),
  Country('CL', 'Chile', 'Chile'),
  Country('CN', 'China', 'China'),
  Country('CY', 'Chipre', 'Cyprus'),
  Country('CO', 'Colombia', 'Colombia'),
  Country('KM', 'Comoras', 'Comoros'),
  Country('KP', 'Corea del Norte', 'North Korea'),
  Country('KR', 'Corea del Sur', 'South Korea'),
  Country('CI', 'Costa de Marfil', "Côte d'Ivoire"),
  Country('CR', 'Costa Rica', 'Costa Rica'),
  Country('HR', 'Croacia', 'Croatia'),
  Country('CU', 'Cuba', 'Cuba'),
  Country('DK', 'Dinamarca', 'Denmark'),
  Country('DM', 'Dominica', 'Dominica'),
  Country('EC', 'Ecuador', 'Ecuador'),
  Country('EG', 'Egipto', 'Egypt'),
  Country('SV', 'El Salvador', 'El Salvador'),
  Country('AE', 'Emiratos Árabes Unidos', 'United Arab Emirates'),
  Country('ER', 'Eritrea', 'Eritrea'),
  Country('SK', 'Eslovaquia', 'Slovakia'),
  Country('SI', 'Eslovenia', 'Slovenia'),
  Country('ES', 'España', 'Spain'),
  Country('US', 'Estados Unidos', 'United States'),
  Country('EE', 'Estonia', 'Estonia'),
  Country('SZ', 'Esuatini', 'Eswatini'),
  Country('ET', 'Etiopía', 'Ethiopia'),
  Country('PH', 'Filipinas', 'Philippines'),
  Country('FI', 'Finlandia', 'Finland'),
  Country('FJ', 'Fiyi', 'Fiji'),
  Country('FR', 'Francia', 'France'),
  Country('GA', 'Gabón', 'Gabon'),
  Country('GM', 'Gambia', 'Gambia'),
  Country('GE', 'Georgia', 'Georgia'),
  Country('GH', 'Ghana', 'Ghana'),
  Country('GD', 'Granada', 'Grenada'),
  Country('GR', 'Grecia', 'Greece'),
  Country('GT', 'Guatemala', 'Guatemala'),
  Country('GY', 'Guyana', 'Guyana'),
  Country('GN', 'Guinea', 'Guinea'),
  Country('GQ', 'Guinea Ecuatorial', 'Equatorial Guinea'),
  Country('GW', 'Guinea-Bisáu', 'Guinea-Bissau'),
  Country('HT', 'Haití', 'Haiti'),
  Country('HN', 'Honduras', 'Honduras'),
  Country('HK', 'Hong Kong', 'Hong Kong'),
  Country('HU', 'Hungría', 'Hungary'),
  Country('IN', 'India', 'India'),
  Country('ID', 'Indonesia', 'Indonesia'),
  Country('IQ', 'Irak', 'Iraq'),
  Country('IR', 'Irán', 'Iran'),
  Country('IE', 'Irlanda', 'Ireland'),
  Country('IS', 'Islandia', 'Iceland'),
  Country('MH', 'Islas Marshall', 'Marshall Islands'),
  Country('SB', 'Islas Salomón', 'Solomon Islands'),
  Country('IL', 'Israel', 'Israel'),
  Country('IT', 'Italia', 'Italy'),
  Country('JM', 'Jamaica', 'Jamaica'),
  Country('JP', 'Japón', 'Japan'),
  Country('JO', 'Jordania', 'Jordan'),
  Country('KZ', 'Kazajistán', 'Kazakhstan'),
  Country('KE', 'Kenia', 'Kenya'),
  Country('KG', 'Kirguistán', 'Kyrgyzstan'),
  Country('KI', 'Kiribati', 'Kiribati'),
  Country('KW', 'Kuwait', 'Kuwait'),
  Country('LA', 'Laos', 'Laos'),
  Country('LS', 'Lesoto', 'Lesotho'),
  Country('LV', 'Letonia', 'Latvia'),
  Country('LB', 'Líbano', 'Lebanon'),
  Country('LR', 'Liberia', 'Liberia'),
  Country('LY', 'Libia', 'Libya'),
  Country('LI', 'Liechtenstein', 'Liechtenstein'),
  Country('LT', 'Lituania', 'Lithuania'),
  Country('LU', 'Luxemburgo', 'Luxembourg'),
  Country('MK', 'Macedonia del Norte', 'North Macedonia'),
  Country('MG', 'Madagascar', 'Madagascar'),
  Country('MY', 'Malasia', 'Malaysia'),
  Country('MW', 'Malaui', 'Malawi'),
  Country('MV', 'Maldivas', 'Maldives'),
  Country('ML', 'Malí', 'Mali'),
  Country('MT', 'Malta', 'Malta'),
  Country('MA', 'Marruecos', 'Morocco'),
  Country('MU', 'Mauricio', 'Mauritius'),
  Country('MR', 'Mauritania', 'Mauritania'),
  Country('MX', 'México', 'Mexico'),
  Country('FM', 'Micronesia', 'Micronesia'),
  Country('MD', 'Moldavia', 'Moldova'),
  Country('MC', 'Mónaco', 'Monaco'),
  Country('MN', 'Mongolia', 'Mongolia'),
  Country('ME', 'Montenegro', 'Montenegro'),
  Country('MZ', 'Mozambique', 'Mozambique'),
  Country('NA', 'Namibia', 'Namibia'),
  Country('NR', 'Nauru', 'Nauru'),
  Country('NP', 'Nepal', 'Nepal'),
  Country('NI', 'Nicaragua', 'Nicaragua'),
  Country('NE', 'Níger', 'Niger'),
  Country('NG', 'Nigeria', 'Nigeria'),
  Country('NO', 'Noruega', 'Norway'),
  Country('NZ', 'Nueva Zelanda', 'New Zealand'),
  Country('OM', 'Omán', 'Oman'),
  Country('NL', 'Países Bajos', 'Netherlands'),
  Country('PK', 'Pakistán', 'Pakistan'),
  Country('PW', 'Palaos', 'Palau'),
  Country('PA', 'Panamá', 'Panama'),
  Country('PG', 'Papúa Nueva Guinea', 'Papua New Guinea'),
  Country('PY', 'Paraguay', 'Paraguay'),
  Country('PE', 'Perú', 'Peru'),
  Country('PL', 'Polonia', 'Poland'),
  Country('PT', 'Portugal', 'Portugal'),
  Country('PR', 'Puerto Rico', 'Puerto Rico'),
  Country('GB', 'Reino Unido', 'United Kingdom'),
  Country('CF', 'República Centroafricana', 'Central African Republic'),
  Country('CZ', 'República Checa', 'Czech Republic'),
  Country('CG', 'República del Congo', 'Republic of the Congo'),
  Country('CD', 'República Democrática del Congo', 'Democratic Republic of the Congo'),
  Country('DO', 'República Dominicana', 'Dominican Republic'),
  Country('RW', 'Ruanda', 'Rwanda'),
  Country('RO', 'Rumania', 'Romania'),
  Country('RU', 'Rusia', 'Russia'),
  Country('WS', 'Samoa', 'Samoa'),
  Country('KN', 'San Cristóbal y Nieves', 'Saint Kitts and Nevis'),
  Country('SM', 'San Marino', 'San Marino'),
  Country('VC', 'San Vicente y las Granadinas', 'Saint Vincent and the Grenadines'),
  Country('LC', 'Santa Lucía', 'Saint Lucia'),
  Country('ST', 'Santo Tomé y Príncipe', 'São Tomé and Príncipe'),
  Country('SN', 'Senegal', 'Senegal'),
  Country('RS', 'Serbia', 'Serbia'),
  Country('SC', 'Seychelles', 'Seychelles'),
  Country('SL', 'Sierra Leona', 'Sierra Leone'),
  Country('SG', 'Singapur', 'Singapore'),
  Country('SY', 'Siria', 'Syria'),
  Country('SO', 'Somalia', 'Somalia'),
  Country('LK', 'Sri Lanka', 'Sri Lanka'),
  Country('ZA', 'Sudáfrica', 'South Africa'),
  Country('SD', 'Sudán', 'Sudan'),
  Country('SS', 'Sudán del Sur', 'South Sudan'),
  Country('SE', 'Suecia', 'Sweden'),
  Country('CH', 'Suiza', 'Switzerland'),
  Country('SR', 'Surinam', 'Suriname'),
  Country('TH', 'Tailandia', 'Thailand'),
  Country('TW', 'Taiwán', 'Taiwan'),
  Country('TZ', 'Tanzania', 'Tanzania'),
  Country('TJ', 'Tayikistán', 'Tajikistan'),
  Country('TL', 'Timor Oriental', 'Timor-Leste'),
  Country('TG', 'Togo', 'Togo'),
  Country('TO', 'Tonga', 'Tonga'),
  Country('TT', 'Trinidad y Tobago', 'Trinidad and Tobago'),
  Country('TN', 'Túnez', 'Tunisia'),
  Country('TM', 'Turkmenistán', 'Turkmenistan'),
  Country('TR', 'Turquía', 'Turkey'),
  Country('TV', 'Tuvalu', 'Tuvalu'),
  Country('UA', 'Ucrania', 'Ukraine'),
  Country('UG', 'Uganda', 'Uganda'),
  Country('UY', 'Uruguay', 'Uruguay'),
  Country('UZ', 'Uzbekistán', 'Uzbekistan'),
  Country('VU', 'Vanuatu', 'Vanuatu'),
  Country('VA', 'Ciudad del Vaticano', 'Vatican City'),
  Country('VE', 'Venezuela', 'Venezuela'),
  Country('VN', 'Vietnam', 'Vietnam'),
  Country('YE', 'Yemen', 'Yemen'),
  Country('DJ', 'Yibuti', 'Djibouti'),
  Country('ZM', 'Zambia', 'Zambia'),
  Country('ZW', 'Zimbabue', 'Zimbabwe'),
];
